
### 

POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "lilian@gmail.com",
  "password": "Lilian1234"
}


### 

# @attach-cookie-jar
POST http://localhost:5000/api/workspaces/create
Content-Type: application/json

{
 "name": "anotherone"
}

### 
# @attach-cookie-jar
GET http://localhost:5000/api/workspaces

###
# @attach-cookie-jar
DELETE http://localhost:5000/api/workspaces/delete/c5ff38ab-fe74-4273-a668-72cd0706d071

### 
# @attach-cookie-jar
PUT http://localhost:5000/api/workspaces/update/5444bdc1-b483-4039-bb4e-441295d7c25c
Content-Type: application/json

{ "name": "updated-workspace"}

### 
# @attach-cookie-jar
POST http://localhost:5000/api/projects/workspace/480547b3-f25b-45a6-a9cf-1c1584c9f067/create
Content-Type: application/json

{ 
  "name": "first-project"
}

### 
# @attach-cookie-jar
GET http://localhost:5000/api/projects/workspace/480547b3-f25b-45a6-a9cf-1c1584c9f067
